name: QTYBox
author: tnyari
category: Forms
tags: [forms, input, gui, controller, element]
docs: https://github.com/tnyari/QTYBox/wiki/QTYBox-usage
demo: http://tnyari.github.com/QTYBox/demo.html
current: 0.1

